# RP-0 tech tree.
#
# This tree is in YAML format.
# 
# Please *only* puts things in here if they should be moved from
# their original positions.
#
# You can convert it into ModuleManager directives by running:
#
#       perl bin/yml2mm
#
# Don't have Perl? Try DWIM Perl!
#
#       http://dwimperl.com/

start:
#TL0. early tech. Sounding rockets, basic structural pieces and wings. Late 40s.
    trussPiece1x:

    # What's this cool ampersand? It's a label. See below as to why we want that:
    longAntenna: &longAntenna
        cost: 5
        entryCost: 0

    # Look! We can say this part is the same as some other part. Bam! No repetition.
    SXTAntenna: *longAntenna

    # Parachutes

    parachuteSingle:
        cost: 10
    parachuteDrogue:
        cost: 15
    parachuteRadial:
        cost: 15
    parachuteLarge:
        cost: 30

    # Starting science

    sensorThermometer:
        cost: 9
    sensorBarometer:
        cost: 20

    KzInterstageAdapter2:
    KzResizableFairingBase:
    KzResizableFairingBaseRing:
    KzProcFairingSide1:
    KzProcFairingSide2:
    noseCone:
    standardNoseCone:
    SXTProtonlikeNoseCone:
    wingConnector4:
    wingConnector5:
    structuralWing4:
    delta_small:
    wingConnector3:
    structuralWing3:
    LMiniAircaftTail:
    StandardCtrlSrf:
    smallCtrlSrf:
    wingStrake:
    rocketNoseCone:
    winglet:
    wingConnector:
    wingConnector2:
    structuralWing:
    structuralWing2:
    sweptWing1:
    sweptWing2:
    elevon2:
    tailfin:
    winglet3:
    deltaWing:
    sweptWing:
    R8winglet:
    elevon3:
    airplaneTail:
    CircularIntake:
    SXTWingSmall:
    CanardController:
    MK1IntakeFuselage:
    AdvancedCanard:
    elevon5:
    IntakeRadialLong:
    airScoop:
    LRadialAirIntake:
    SXTInlineAirIntake:
    SXTInlineAirIntakeTiny:
    nacelleBody:
    radialEngineBody:
    ladder1:
    spotLight1:
    spotLight2:
    SmallGearBay:
    structuralIBeam3:
    strutCube:
    strutOcto:
    structuralIBeam2:
    structuralMiniNode:
    trussPiece1x:
    structuralPanel1:
    strutConnector:
    structuralIBeam1:
    trussAdapter:
    trussPiece3x:
    structuralPanel2:
    KzProcFairingFuselage1:
    KzProcFairingFuselage2:
    KzThrustPlate:
    launchClamp1:
        cost: 10
    stackDecouplerMini:
    smallHardpoint:
    structuralPylon:
    sepMotor1:
    SXTSmallFuselage:
    miniFuelTank:
    rcsTankMini:
    SXTFuel625m:
    SnubOtron:
    RP0probeSounding0-3m:
# modeled on the electronics of WAC Corporal / Aerobee
    ROAerobeeSustainer:
#Early Aerojet engine, used on WAC Corporal and Aerobee. Very small and low efficency.
    OscarDtank:
    OscarEtank:
    Proceduralwing2:
    Proceduralwing2EndPiece:
    Proceduralwing4:
    ProceduralAllMovingWing:
    ProceduralwingBac9:
    ProceduralwingSPP:
    pCtrlSrf1:
    B9_Aero_Wing_ControlSurface_SH_4mProcedural:
# Basic RemoteTech antenna, so things can get off the ground. :)
    RTShortAntenna1:

basicRocketry:
# Batteries; since players already have service modules.
    batteryPack:
    batteryBankMini:
    ksp_r_largeBatteryPack:
#TL 0/1: Vanguard, early-mid 50s tech. For now includes Black Arrow (FIXME)
    fuelTankSmallFlat:
    fuelTank:
    GooExperiment:
    stackDecoupler:
    SXTWaxWing:
#(Black Arrow kick motor)
    SXTBlackAdder2:
#Gamma 2 (Black Arrow upper stage engine)
    toroidalFuelTank:
    fuelTankSmall:
    SXTBlackAdder:
#Gamma 8 (Black Arrow main engine)
    SXTSputnik:
    radialRCSTank:
    MK1Fuselage:
    RCSFuelTank:
    rcsTankRadialLong:
    liquidEngine2:
#X-405 (Vanguard main engine)
    fuelTank_long:
    RO-AJ10-Early:
#(Vanguard/Able/[Early]Delta upper stage)

generalRocketry:
#TL1/2 Late 1950s/1960 tech, first real orbital LVs. Atlas, R-7, etc.
    liquidEngine3:
#11D33 (Molniya upper stage)
    RO-LR-89:
#LR-79/89 (Thor/Jupiter main engine, Atlas booster)
    RCSTank1-2:
    fuelTank4-2:
    fuelTank2-2:
    fuelTank1-2:
    fuelTank3-2:
    radialEngineMini:
#LR-101 vernier (Thor/Jupiter/Atlas)

survivability:
#First crewed capsules
    mk1pod:
        entryCost: 60000 # Full 100x
        cost: 6000

stability:
#3-axis stability in orbit. CORONA etc.
    noseCone:
    winglet:
    radialDecoupler:
    RCSBoonExt:
    SquadRCSBlockHalf:
    RCSBlockQuarter:

advRocketry:
# TL2 1960-65 tech or so. Gemini, Voskhod, etc.
    liquidEngine:
    solidBooster:
    solidBooster1-1:
    M55:

scienceTech:

generalConstruction:

flightControl:

advConstruction:

advFlightControl:

electrics:

spaceExploration:

landing:

heavyRocketry:
#TL3 Mid-late 60s tech. Saturn V, N-1.
    solidBooster1-1Small:
# NOTE: This ^^ is going to change to a Castor 1, and be moved to advRocketry.

fuelSystems:

aerodynamicSystems:

advExploration:

precisionEngineering:

advElectrics:

specializedControl:

heavierRocketry:
#TL4 Apollo Applications program, working N-1, etc.


specializedConstruction:

advLanding:

supersonicFlight:

actuators:

composites:

fieldScience:

nuclearPropulsion:

ionPropulsion:

largeElectrics:

electronics:

highAltitudeFlight:

unmannedTech:

largeControl:

advMetalWorks:

advAerodynamics:

metaMaterials:

heavyAerodynamics:

veryHeavyRocketry:
#TL5 80s tech
    engineLargeSkipper_125m:
    liquidEngineMiniRescale:
    solidBoosterSmall:

advancedMotors:

hypersonicFlight:

specializedElectrics:

advUnmanned:

advScienceTech:

experimentalRocketry:

aerospaceTech:

experimentalElectrics:

experimentalAerodynamics:

experimentalScience:

experimentalMotors:

robotics:

automation:

nanolathing:

specializedScienceTech:

nuclearPower:

largeNuclearPower:

nuclearFuelSystems:

advNuclearPower:

nuclearSupport:

improvedNuclearPropulsion:

advNuclearPropulsion:

fusionRockets:

giganticRocketry:

colossalRocketry:

fusionPower:

exoticAlloys:

orbitalAssembly:

advAerospaceComposites:

expAircraftEngines:

heavyControl:

subsonicFlight:

offworldManufacturing:

orbitalSurveys:

advSurveys:

recycling:

hydroponics:

longTermHabitation:

resourceUtilization:

offworldMining:

advOffworldMining:

resourceExploitation:

selfSufficientOutposts:

specializedScienceTech:

longTermScienceTech:

scientificOutposts:

advSolarTech:

cuttingEdgeSolarTech:

advPVMaterials:

electricalSystems:

advIonPropulsion:

plasmaPropulsion:

experimentalIonPropulsion:

cuttingEdgeIonPropulsion:

advPlasmaPropulsion:

exoticReactions:

highEnergyScience:

orbitalMegastructures:

specializedPlasmaTech:

powerTransmission:

antimatterPower:

ultraHighEnergyPhysics:

enhancedSurvivability:

shortTermHabitation:

