# RP-0 tech tree.
#
# This tree is in YAML format.
# 
# Please *only* puts things in here if they should be moved from
# their original positions.
#
# You can convert it into ModuleManager directives by running:
#
#       perl bin/yml2mm
#
# Don't have Perl? Try DWIM Perl!
#
#       http://dwimperl.com/

start:
#TL0. early tech. Sounding rockets, basic structural pieces and wings. Late 40s.

    # Parachutes

    parachuteSingle:
        cost: 10
    parachuteDrogue:
        cost: 15
    parachuteRadial:
        cost: 15
    parachuteLarge:
        cost: 30

    # Starting science

    sensorThermometer:
        cost: 9

    sensorBarometer:
        cost: 20

    # What's this cool ampersand? It's a label. See below as to why we want that:
    longAntenna: &longAntenna
        cost: 5
        entryCost: 0

    # Look! We can say this part is the same as some other part. Bam! No repetition.
    SXTAntenna: *longAntenna

    # Basic RemoteTech antenna, so things can get off the ground. :)
    RTShortAntenna1:

    # Fairings

    KzInterstageAdapter2:
    KzProcFairingFuselage1:
    KzProcFairingFuselage2:
    KzProcFairingSide1:
    KzProcFairingSide2:
    KzResizableFairingBase:
    KzResizableFairingBaseRing:

    # Nose Cones

    noseCone:
    rocketNoseCone:
    standardNoseCone:
    SXTProtonlikeNoseCone:

    # Wings

    airplaneTail:
    B9_Aero_Wing_ControlSurface_SH_4mProcedural:
    delta_small:
    deltaWing:
    elevon2:
    elevon3:
    LMiniAircaftTail:
    pCtrlSrf1:
    ProceduralAllMovingWing:
    Proceduralwing2:
    Proceduralwing2EndPiece:
    Proceduralwing4:
    ProceduralwingBac9:
    ProceduralwingSPP:
    R8winglet:
    smallCtrlSrf:
    StandardCtrlSrf:
    structuralWing:
    structuralWing2:
    structuralWing3:
    structuralWing4:
    sweptWing:
    sweptWing1:
    sweptWing2:
    SXTWingSmall:
    tailfin:
    wingConnector:
    wingConnector2:
    wingConnector3:
    wingConnector4:
    wingConnector5:
    winglet:
    winglet3:
    wingStrake:

    # Intakes

    airScoop:
    CircularIntake:
    IntakeRadialLong:
    LRadialAirIntake:
    MK1IntakeFuselage:
    SXTInlineAirIntake:
    SXTInlineAirIntakeTiny:

    # Structural
    
    smallHardpoint:
    structuralIBeam1:
    structuralIBeam2:
    structuralIBeam3:
    structuralMiniNode:
    structuralPanel1:
    structuralPanel2:
    structuralPylon:
    strutConnector:
    strutCube:
    strutOcto:
    SXTSmallFuselage:
    trussAdapter:
    trussPiece1x:
    trussPiece1x:
    trussPiece3x:

    # Lights, ladders and things

    ladder1:
    spotLight1:
    spotLight2:

    # Engines

    sepMotor1:
        cost: 7

    # Small solid
    SnubOtron:
        entryCost: 0
        cost: 3

    RP0probeSounding0-3m:
        entryCost: 0
        cost: 1

    # modeled on the electronics of WAC Corporal / Aerobee
    # Early Aerojet engine, used on WAC Corporal and Aerobee. Very small and low efficency.
    ROAerobeeSustainer:
        entryCost: 0
        cost: 6

    # Tanks

    SXTFuel625m:
    miniFuelTank:
    rcsTankMini:
    OscarDtank:
    OscarEtank:

    # Unsorted. Please sort me! ;)

    CanardController:
    AdvancedCanard:
    elevon5:
    nacelleBody:
    radialEngineBody:
    SmallGearBay:
    KzThrustPlate:
    launchClamp1:
        cost: 10
    stackDecouplerMini:
        cost: 2
    radialDecoupler:
        cost: 20

#TL 0/1: Vanguard, early-mid 50s tech. For now includes Black Arrow (FIXME)
basicRocketry:

    # Batteries; since players already have service modules.

    batteryPack:
    batteryBankMini:
    ksp_r_largeBatteryPack:

    # Tanks

    fuelTankSmallFlat:
    fuelTank:
    toroidalFuelTank:
    fuelTankSmall:
    radialRCSTank:
    MK1Fuselage:
    RCSFuelTank:
    rcsTankRadialLong:
    fuelTank_long:

    # New probe!

    SXTSputnik:

    # !!SCIENCE!!

    # Stock goo experiment
    GooExperiment:
        cost: 15

    # Goo in a can (stack mount)
    SXTProbeGooo:
        cost: 20

    # Goo as a science wedge (from DMagic Orbital Science)
    # Expensive, because wedges are cool.
    dmUSGoo:
        cost: 50

    # Decoupler

    stackDecoupler:

    # Universal Storage structural

    # Wedges are relatively expensive, because they've got to be
    # wired for interchangeable components.
    US.c.Hub.QuadCore:
        cost: 200

    # The decoupler is pretty cheap, because other decouplers are, too.
    US.f.Dec.SafetyDecoupler125:
        cost: 10

    # Engines

    SXTWaxWing: # Black Arrow kick motor
        entryCost: 8000
        cost: 400 # stage cost $1mil WHAT?

    SXTBlackAdder: # Gamma 8 (Black Arrow main engine)
        entryCost: 24000
        cost: 1200 # Stage cost 4m

    SXTBlackAdder2: #Gamma 2 (Black Arrow upper stage engine)
        entryCost: 12000
        cost: 600 # Stage cost $3m in 1970, but avionics probably a large part

    liquidEngine2: # X-405 (Vanguard main engine)
        entryCost: 18000
        cost: 900

    RO-AJ10-Early: # (Vanguard/Able/[Early]Delta upper stage)
        entryCost: 3000
        cost: 150

# TL1/2 Late 1950s/1960 tech, first real orbital LVs. Atlas, R-7, etc.
generalRocketry:

    # Blok E (Luna/Vostok), Blok L (Molniya) fourth stage engine
    liquidEngine3:
        entryCost: 12000
        cost: 600

    # LR-79/89 (Thor/Jupiter main engine, Atlas booster)
    RO-LR-89:
        entryCost: 40000
        cost: 2000

    RCSTank1-2:
    fuelTank4-2:
    fuelTank2-2:
    fuelTank1-2:
    fuelTank3-2:

    # LR-101 vernier (Thor/Jupiter/Atlas)
    radialEngineMini:
        entryCost: 1000
        cost: 50

survivability:
#First crewed capsules
    mk1pod:
        entryCost: 88000 # 40m from below, plus assumed extra R&D from other programs
        cost: 4400 # source: _This New Ocean_ with recurring cost + amortized other costs.
#Heatshields
    0625_Heatshield:	    
        entryCost: 6000
        cost: 300
    Heatshield-1M:
        entryCost: 12000
        cost: 600
    1.25_Heatshield:
        entryCost: 20000
        cost: 1000

stability:
#3-axis stability in orbit. CORONA etc.

    # RCS joy.

    RCSBoonExt:
        # TODO: Make sure my costs are sane!

    SquadRCSBlockHalf:
        entryCost: 2000 # breaks 20x rule because of avionics required
        cost: 20

    RCSBlockQuarter:
        entryCost: 1000
        cost: 15

advRocketry:
# TL2 1960-65 tech or so. Gemini, Voskhod, etc.
    liquidEngine:
    solidBooster:
    solidBooster1-1:
    M55:

scienceTech:

generalConstruction:

flightControl:

advConstruction:

advFlightControl:

electrics:

spaceExploration:

landing:

heavyRocketry:
#TL3 Mid-late 60s tech. Saturn V, N-1.
    solidBooster1-1Small:
# NOTE: This ^^ is going to change to a Castor 1, and be moved to advRocketry.

fuelSystems:

aerodynamicSystems:

advExploration:

precisionEngineering:

advElectrics:

specializedControl:

heavierRocketry:
#TL4 Apollo Applications program, working N-1, etc.


specializedConstruction:

advLanding:

supersonicFlight:

actuators:

composites:

fieldScience:

nuclearPropulsion:

ionPropulsion:

largeElectrics:

electronics:

highAltitudeFlight:

unmannedTech:

largeControl:

advMetalWorks:

advAerodynamics:

metaMaterials:

heavyAerodynamics:

veryHeavyRocketry:
#TL5 80s tech
    engineLargeSkipper_125m:
    liquidEngineMiniRescale:
    solidBoosterSmall:

advancedMotors:

hypersonicFlight:

specializedElectrics:

advUnmanned:

advScienceTech:

experimentalRocketry:

aerospaceTech:

experimentalElectrics:

experimentalAerodynamics:

experimentalScience:

experimentalMotors:

robotics:

automation:

# FIXME this is our catchall node
nanolathing:

    # Good try attemping to put heatshields in here. Most are generated
    # in RO_DeadlyReEntry.cfg in a FINAL pass, so good luck catching
    # that!

#DRE heatshields
    2.5_Heatshield:
    3.75_Heatshield:
    6.25_Heatshield:
#RO Heatshields
    Heatshield-2M:
    Heatshield-3M:
    Heatshield-375M:
    Heatshield-4M:
    Heatshield-5M:
    Heatshield-10M:
    Heatshield-15M:
    Heatshield-25M:

    # Let's build a truck!
    SXTtruckcabinsmall:
    SXTtruckcabin:
   
specializedScienceTech:

nuclearPower:

largeNuclearPower:

nuclearFuelSystems:

advNuclearPower:

nuclearSupport:

improvedNuclearPropulsion:

advNuclearPropulsion:

fusionRockets:

giganticRocketry:

colossalRocketry:

fusionPower:

exoticAlloys:

orbitalAssembly:

advAerospaceComposites:

expAircraftEngines:

heavyControl:

subsonicFlight:

offworldManufacturing:

orbitalSurveys:

advSurveys:

recycling:

    # Water Recycling System
    US_Wedge_WRS:

    # CO2 removal
    US_Wedge_Sabatier:

hydroponics:

longTermHabitation:

resourceUtilization:

offworldMining:

advOffworldMining:

resourceExploitation:

selfSufficientOutposts:

specializedScienceTech:

longTermScienceTech:

scientificOutposts:

advSolarTech:

cuttingEdgeSolarTech:

advPVMaterials:

electricalSystems:

advIonPropulsion:

plasmaPropulsion:

experimentalIonPropulsion:

cuttingEdgeIonPropulsion:

advPlasmaPropulsion:

exoticReactions:

highEnergyScience:

orbitalMegastructures:

specializedPlasmaTech:

powerTransmission:

antimatterPower:

ultraHighEnergyPhysics:

enhancedSurvivability:
    # This comes after regular survivability, so let's add some cool tech here!
   
    US_Wedge_Carbon:
    US_Wedge_Food:
    US_q_Wedge_Water:           # Yes, the _q_ is correct
    US_Wedge_Waste:
    US_Wedge_WasteWater:
    US_m_Wedge:Oxygen:          # Yes, the _m_ is correct

shortTermHabitation:

